module:
  auto_entitylabel: 0
  automated_cron: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contextual: 0
  datetime: 0
  dblog: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  jwt: 0
  jwt_auth_consumer: 0
  jwt_auth_issuer: 0
  key: 0
  layout_discovery: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  prepopulate: 0
  quickedit: 0
  quip: 0
  rdf: 0
  rest: 0
  restui: 0
  serialization: 0
  system: 0
  tac_lite_create: 0
  taxonomy: 0
  taxonomy_unique: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_taxonomy_term_name_depth: 0
  views_ui: 0
  ds: 1
  hide_revision_field: 1
  menu_link_content: 1
  ds_extras: 2
  views: 10
  tac_lite: 100
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  drupal8_w3css_theme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
