drupalAcctProvisionServer: tciabeta
ldapEntryProvisionServer: null
drupalAcctProvisionTriggers:
  - drupal_on_login
ldapEntryProvisionTriggers: {  }
userUpdateCronQuery: none
userUpdateCronInterval: daily
orphanedDrupalAcctBehavior: ldap_user_orphan_email
orphanedDrupalAcctReportingInbox: ''
orphanedCheckQty: 100
orphanedAccountCheckInterval: weekly
userConflictResolve: resolve
manualAccountConflict: conflict_reject
acctCreation: ldap_behaviour
ldapUserSyncMappings:
  drupal: {  }
_core:
  default_config_hash: xGaDFlyXTmhzluhiRhEx58v_3Fu-nMhCzEBF8K4eqHU
disableAdminPasswordField: false
