tac_lite_categories:
  collections: collections
tac_lite_schemes: '3'
menu_rebuild_needed: true
_core:
  default_config_hash: O3rsbjEveBvnof1Hdq3ih8UBqlRN2betEk9OZhaiTPM
tac_lite_config_scheme_1:
  name: Read
  perms:
    grant_view: grant_view
  unpublished: 0
  term_visibility: 0
  tac_lite_create: 0
tac_lite_grants_scheme_1:
  anonymous:
    collections:
      2: '2'
  authenticated:
    collections:
      2: '2'
  administrator:
    collections:
      - '0'
  editor:
    collections:
      - '0'
tac_lite_config_scheme_2:
  name: Read/Write
  perms:
    grant_view: grant_view
    grant_update: grant_update
  unpublished: 0
  term_visibility: 0
  tac_lite_create: 0
tac_lite_grants_scheme_2:
  anonymous:
    collections: {  }
  authenticated:
    collections: {  }
  administrator:
    collections: {  }
  editor:
    collections: {  }
tac_lite_config_scheme_3:
  name: Read/Write/Delete
  perms:
    grant_view: grant_view
    grant_update: grant_update
    grant_delete: grant_delete
  unpublished: 0
  term_visibility: 0
  tac_lite_create: 0
tac_lite_grants_scheme_3:
  anonymous:
    collections: {  }
  authenticated:
    collections: {  }
  administrator:
    collections: {  }
  editor:
    collections: {  }
